# Generated by Django 5.1.7 on 2025-03-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='watchlist_app.streamplatform'),
        ),
    ]
